export const listFramework = [
  { value: "javascript", name: "JavaScript" },
  { value: "typescript", name: "TypeScript" },
  { value: "python", name: "Python" },
  { value: "c", name: "C" },
  { value: "c++", name: "C++" },
  { value: "java", name: "Java" },
  { value: "c#", name: "C#" },
  { value: "go", name: "Go" },
  { value: "rust", name: "Rust" },
  { value: "ruby", name: "Ruby" },
  { value: "php", name: "Php" },
  { value: "kotlin", name: "Kotlin" },
  { value: "swift", name: "Swift" },
  { value: "scala", name: "Scala" },
  { value: "dart", name: "Dart" },
  { value: "bash", name: "Bash" },
  { value: "sql", name: "Sql" },
  { value: "html", name: "Html" },
  { value: "css", name: "Css" },
];
